### ISSUE TITLE
how to use length

### ISSUE THREAD

**Issue by wanghaisheng** [LuisMayo/objection_engine#46]
```
                if "length" in obj:
                    _length = obj["length"]
```
if input is a second ,how to convert it into length variable?
it seems to be fps related,and default fps is 10 in video.py,how can I define  and use length in scene.py ?

**Comment by LuisMayo** [comment]
Hi again!
I think I don't properly understand.

Would you care to explain what are you trying to do?

Thanks!

**Comment by LuisMayo** [comment]
Hi, in order for me to assist you with this one, I would want to know how are things now exactly. Have you progressed since the last post?
Thanks!
