### ISSUE TITLE
Add the ability to take an input array and parse it to the proper format

### ISSUE THREAD

**Issue by LuisMayo** [LuisMayo/objection_engine#6]

**Comment by saschanaz** [comment]
I'd like to take a look at this, but not sure what this is about. `render_comment_list` already takes a list, what should be changed here?

**Comment by LuisMayo** [comment]
And you're right.

This seems to be a leftover from when the repo wasn't even objection_engine but a mod from the reddit bot

You're right, this is already done. I'm closing this
