### ISSUE TITLE
Installation instructions not working with Python 3.9.6 on macOS 12.6

### ISSUE THREAD

**Issue by Meorge** [LuisMayo/objection_engine#81]
I'd like to experiment with and potentially contribute to this project, but the installation/setup instructions aren't working for me:
```zsh
➜  Repositories git clone https://github.com/LuisMayo/objection_engine
Cloning into 'objection_engine'...
remote: Enumerating objects: 793, done.
remote: Counting objects: 100% (354/354), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 793 (delta 290), reused 292 (delta 256), pack-reused 439
Receiving objects: 100% (793/793), 192.87 KiB | 3.44 MiB/s, done.
Resolving deltas: 100% (477/477), done.

➜  Repositories cd ./objection_engine 

➜  objection_engine git:(main) python3.9 --version
Python 3.9.15

➜  objection_engine git:(main) python3.9 -m pip install -r pyproject.toml 
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
ERROR: Invalid requirement: '[tool.poetry]' (from line 1 of pyproject.toml)
```

This is running on an Intel iMac, macOS Monterey 12.6. If you need/would like more info to help determine the issue, I'm happy to provide it.
Thanks!

**Update:** Using Poetry (not pip) I was able to install the dependencies and run `example.py` successfully to generate a video! I'm not sure if the installation documentation is out of date, or if there was some issue with my installation of Python that was causing it to not work, but if it's the former, then it'd be good to update it.

**Comment by LuisMayo** [comment]
Sorry. You were right on your edit., this project now uses poetry to manage dependencies

It seems this was a regression introduced in #75. I'll fix it when I can.

Please keep contacting with any other troubles yo may find while contributing.
Thanks!
