### ISSUE TITLE
Replace "next dialogue" arrow with a GIF

### ISSUE THREAD

**Issue by Meorge** [LuisMayo/objection_engine#94]
Currently, the way the "next dialogue" arrow is animated is by starting with the static arrow image, then adding a different amount of padding to it for several frames. You can see it in this example from when I was working on the improved Arabic support:

https://user-images.githubusercontent.com/9957987/201006718-82a7ecfa-0b24-4d33-a6d2-fdae108f9110.mp4

This seems like a rather weird and hacky way to do this; I think it'd be better to just make the moving arrow into an independent GIF, and then play that on loop the same way the characters are currently animated. It would also simplify the code for the left-pointing arrow.

**Comment by LuisMayo** [comment]
Totally agree. Good report!
